name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Authenticate with Azure using Service Principal
      - name: Authenticate with Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform
      - name: Terraform Plan
        run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                            -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                            -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
                            -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}"

      # Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                                          -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                                          -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
                                          -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}"
