name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          }

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.REGISTRY_NAME }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME="${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:${{ github.sha }}"
        docker build . -t $IMAGE_NAME
        docker push $IMAGE_NAME
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name "${{ secrets.CONTAINER_APP_NAME }}" \
          --resource-group "${{ secrets.RESOURCE_GROUP }}" \
          --image "${{ env.IMAGE_NAME }}"
