name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AZURE_API_VERSION: "2024-03-01" # Use one of the supported versions from the error message

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      # Update Azure CLI
      - name: Update Azure CLI
        run: |
          az upgrade --yes

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Install Latest Azure CLI
      - name: Install Latest Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Check Azure CLI Version
      - name: Check Azure CLI Version
        run: az --version

      # Authenticate with Azure using Service Principal
      - name: Authenticate with Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Zip Static Files
      - name: Zip Static Files
        run: |
          cd public
          zip -r ../public.zip .

      # Deploy Application
      - name: Deploy Application
        run: |
          az webapp deploy \
            --name notepad-frontend1 \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --src-path public.zip \
            --type zip
