name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Authenticate with Azure using Service Principal
      - name: Authenticate with Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform
      - name: Terraform Plan
        run: terraform plan 

      # Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve 


       # Retrieve Web App Name from Terraform Outputs
      - name: Get Web App Name
        id: get_webapp_name
        run: |
          WEB_APP_NAME=$(terraform output -raw web_app_name | tr -d '\r' | tr -d '\n')
          echo "WEB_APP_NAME=$WEB_APP_NAME" >> $GITHUB_ENV

      # Zip Static Files
      - name: Zip Static Files
        run: |
          zip -r public.zip public/

      # Deploy Static Files to Azure Web App
      - name: Deploy Application
        run: |
          az webapp deployment source config-zip \
            --name "${{ env.WEB_APP_NAME }}" \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --src public.zip
