name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Install Latest Azure CLI
      - name: Install Latest Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Authenticate with Azure using Service Principal
      - name: Authenticate with Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve

      

      
